### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by joonan30** [Jack614/jalpc_jekyll_theme#23]
Hi Jack,

Thanks for the great template. I am wondering how to change the theme and icon color - now turquoise used (or light sea green?). Could you tell me which line I should edit?

Many thanks,

**Comment by Jack614** [comment]
Thanks for using my theme,since there are many element having different classes with this color '#1ab394',you can search this string in 'static/css/style.css' and change it to the color you want.
Besides the color '#19aa8d', '#17987e' and '#1cc09f' are other kind of green, it shows on your page's navbar, maybe you need to change as well.

**Comment by joonan30** [comment]
Thanks for the prompt reply. I made changes for colors in 'static/css/style.css' but not really changed the ones. Should I add any modification? I'd like to change the colors for green bars and fa-icons.

Thanks!

**Comment by joonan30** [comment]
Got it. It was 'style.min.css', not 'style.css'. Should I fix the path to use style.css?

**Comment by Jack614** [comment]
Sorry,I forgot I used 'style.min.css'.
Of course you can fix the path and edit it,I think you can get the appearance you want.😄

**Comment by joonan30** [comment]
Thanks!!
