### ISSUE TITLE
Absolute vs relative paths.

### ISSUE THREAD

**Issue by Prakhar0409** [Jack614/jalpc_jekyll_theme#25]
Hi, I think `jekyll build` or `jekyll serve` is adding absolute paths to the template. 
I am trying to host _site folder on a computer and on opening it in the browser, it looks plain html. Clearly, stylesheets and other stuff are not getting included. I suspect this to be because of absolute addressing.

**Comment by Jack614** [comment]
I think it's because browser's security configuration. When I open this file with chrome,js and css files cann't be loaded along with the index page,but when I start a simple http server,like `python -m SimpleHTTPServer` in directory `_site`,the index page is right.
I read `index.html` file ,js and css files are relative path and the path is right.
Do you mean this? Thanks for your question.🙂

**Comment by Prakhar0409** [comment]
Hi, yes it was an issue with file permissions in the css and js folders. Thanks.
